-- RUN FROM SQL EDITOR AS SYSTEM USER

-- CREATE DEVELOPER USER
CREATE USER DEVUSER PASSWORD "Password1";

-- AUTHORIZATIONS
GRANT MODELING TO DEVUSER;
GRANT CREATE SCHEMA TO DEVUSER;
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.ide.roles::Developer','DEVUSER');
